apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic3
    app.kubernetes.io/part-of: application-sample3
  name: devfile-sample-go-basic3
spec:
  ports:
  - name: "1112"
    port: 1112
    targetPort: 1112
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic3
status:
  loadBalancer: {}
